// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAni1_sTS3lgfYk3n5wZeMNirx7mhOU6vo',
    appId: '1:1043089531087:web:80fbaca55ee124fd6ad7ba',
    messagingSenderId: '1043089531087',
    projectId: 'exam-a7a12',
    authDomain: 'exam-a7a12.firebaseapp.com',
    storageBucket: 'exam-a7a12.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZqupkFDagtBNk2bqVRWZx_A9cdIvzUqU',
    appId: '1:1043089531087:android:fa579e67d59c01396ad7ba',
    messagingSenderId: '1043089531087',
    projectId: 'exam-a7a12',
    storageBucket: 'exam-a7a12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQDwrdYW27Xx7D00fNS71huhpbkTvCm9c',
    appId: '1:1043089531087:ios:dd5ceb71e2855bba6ad7ba',
    messagingSenderId: '1043089531087',
    projectId: 'exam-a7a12',
    storageBucket: 'exam-a7a12.appspot.com',
    iosBundleId: 'com.example.flutterFinalExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQDwrdYW27Xx7D00fNS71huhpbkTvCm9c',
    appId: '1:1043089531087:ios:dd5ceb71e2855bba6ad7ba',
    messagingSenderId: '1043089531087',
    projectId: 'exam-a7a12',
    storageBucket: 'exam-a7a12.appspot.com',
    iosBundleId: 'com.example.flutterFinalExam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAni1_sTS3lgfYk3n5wZeMNirx7mhOU6vo',
    appId: '1:1043089531087:web:5c6681abdab114cc6ad7ba',
    messagingSenderId: '1043089531087',
    projectId: 'exam-a7a12',
    authDomain: 'exam-a7a12.firebaseapp.com',
    storageBucket: 'exam-a7a12.appspot.com',
  );
}
